/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Struktury.BazaMiast;

/**
 *
 * @author kuzniarg
 */
public class OknoGeneracji extends javax.swing.JFrame {

    private BazaMiast baza;
    private int aktualny = 0;

    public OknoGeneracji(BazaMiast baza) {
        this.baza = baza;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Generowanie danych - miasto 1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tekstNazwaMiasta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tekstPrzejazd = new javax.swing.JTextField();
        przyciskDalej = new javax.swing.JButton();

        setTitle("Generowanie danych");

        jLabel2.setText("Nazwa miasta");

        jLabel3.setText("Czas przejazu");

        tekstPrzejazd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstPrzejazdActionPerformed(evt);
            }
        });

        przyciskDalej.setText("Dalej");
        przyciskDalej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskDalejActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(przyciskDalej, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tekstNazwaMiasta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tekstPrzejazd, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tekstNazwaMiasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tekstPrzejazd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(przyciskDalej)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tekstPrzejazdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstPrzejazdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tekstPrzejazdActionPerformed

    private void przyciskDalejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskDalejActionPerformed
        this.setTitle("Generowanie danych - miasto " + (aktualny + 2));

        //BLABLABLA//////////////
        aktualny++;
        if (aktualny == baza.getN() - 1) {
            przyciskDalej.setText("Zakończ");
        }
        if (aktualny == baza.getN()) {
            this.wyczysc();
        }
    }//GEN-LAST:event_przyciskDalejActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton przyciskDalej;
    private javax.swing.JTextField tekstNazwaMiasta;
    private javax.swing.JTextField tekstPrzejazd;
    // End of variables declaration//GEN-END:variables

    private void wyczysc() {
        this.aktualny = 0;
        this.setVisible(false);
        this.setTitle("Generowanie danych - miasto 1");
        przyciskDalej.setText("Dalej");
    }
}
