/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Struktury.BazaMiast;
import static aisd_projekt2.Losowanie.Losowanie;

/**
 *
 * @author kuzniarg
 */
public class OknoWybierzN extends javax.swing.JFrame {

    private boolean czyLosowe = false;
    private BazaMiast baza;
    private OknoGeneracji generacja;

    public OknoWybierzN(BazaMiast baza) {
        this.baza = baza;
        generacja = new OknoGeneracji(baza);
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        suwakN = new javax.swing.JSlider();
        przyciskZatwierdz = new javax.swing.JButton();
        czyDaneLosowe = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wybór ilości miast");
        setResizable(false);

        jLabel1.setText("Wybierz liczbę miast, jaką chcesz wygenerować");

        suwakN.setMajorTickSpacing(1);
        suwakN.setMaximum(15);
        suwakN.setMinimum(4);
        suwakN.setPaintLabels(true);
        suwakN.setPaintTicks(true);
        suwakN.setValue(8);

        przyciskZatwierdz.setText("Zatwierdź");
        przyciskZatwierdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskZatwierdzActionPerformed(evt);
            }
        });

        czyDaneLosowe.setText("Dane losowe");
        czyDaneLosowe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czyDaneLosoweActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suwakN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(czyDaneLosowe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przyciskZatwierdz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(suwakN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(przyciskZatwierdz)
                    .addComponent(czyDaneLosowe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void czyDaneLosoweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czyDaneLosoweActionPerformed
        if (czyLosowe) {
            czyLosowe = false;
        } else {
            czyLosowe = true;
        }
    }//GEN-LAST:event_czyDaneLosoweActionPerformed

    private void przyciskZatwierdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskZatwierdzActionPerformed
        baza.wyczysc();
        baza.inicjuj(suwakN.getValue());
        this.setVisible(false);
        if (!czyLosowe) {
            generacja.setVisible(true);
        }
        else{
            Losowanie(baza);
        }
    }//GEN-LAST:event_przyciskZatwierdzActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox czyDaneLosowe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton przyciskZatwierdz;
    private javax.swing.JSlider suwakN;
    // End of variables declaration//GEN-END:variables
}
