/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Struktury.BazaMiast;
import Struktury.Miasto;

/**
 *
 * @author kuzniarg
 */
public class OknoGlowne extends javax.swing.JFrame {

    private BazaMiast baza = new BazaMiast();
    private OknoWybierzN oknoWyboruN = new OknoWybierzN(baza);

    public OknoGlowne() {
        initComponents();
        init();
    }

    private void init() {
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRysuj = new GUI.OknoRysuj();
        przyciskRysowania = new javax.swing.JButton();
        przyciskTestowe = new javax.swing.JButton();
        przyciskGeneracjiDanych = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AiSD Projekt 2");

        javax.swing.GroupLayout panelRysujLayout = new javax.swing.GroupLayout(panelRysuj);
        panelRysuj.setLayout(panelRysujLayout);
        panelRysujLayout.setHorizontalGroup(
            panelRysujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        panelRysujLayout.setVerticalGroup(
            panelRysujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        przyciskRysowania.setText("Rysuj");
        przyciskRysowania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskRysowaniaActionPerformed(evt);
            }
        });

        przyciskTestowe.setText("Dane testowe");
        przyciskTestowe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskTestoweActionPerformed(evt);
            }
        });

        przyciskGeneracjiDanych.setText("Generuj dane");
        przyciskGeneracjiDanych.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskGeneracjiDanychActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelRysuj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(przyciskGeneracjiDanych, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(przyciskTestowe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(przyciskRysowania, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(przyciskRysowania)
                        .addGap(122, 122, 122)
                        .addComponent(przyciskGeneracjiDanych)
                        .addGap(37, 37, 37)
                        .addComponent(przyciskTestowe)
                        .addGap(0, 409, Short.MAX_VALUE))
                    .addComponent(panelRysuj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void przyciskRysowaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskRysowaniaActionPerformed
        panelRysuj.rysuj(baza);
    }//GEN-LAST:event_przyciskRysowaniaActionPerformed

    private void przyciskGeneracjiDanychActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskGeneracjiDanychActionPerformed
        oknoWyboruN.setVisible(true);
    }//GEN-LAST:event_przyciskGeneracjiDanychActionPerformed

    private void przyciskTestoweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskTestoweActionPerformed
        if (baza.getN() == 0) {
            String[] nazwy = {"Warszawa", "Poznań", "Kielce", "Harachwosty", "Mrozy", "Siedlce", "Katowice", "Gdynia",
                "Łosice", "Kraków", "", "", "", "", "", "", "", "", "", ""};
            for (int i = 0; i < 8; i++) {
                baza.setMiasto(i, new Miasto(nazwy[i], 0, baza.getN()));
            }
        }
    }//GEN-LAST:event_przyciskTestoweActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.OknoRysuj panelRysuj;
    private javax.swing.JButton przyciskGeneracjiDanych;
    private javax.swing.JButton przyciskRysowania;
    private javax.swing.JButton przyciskTestowe;
    // End of variables declaration//GEN-END:variables
}
