/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author kuzniarg
 */
public class OknoGeneracji extends javax.swing.JFrame {

    /**
     * Creates new form OknoGeneracji
     */
    public OknoGeneracji() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoTabelaPolaczen1 = new GUI.OknoTabelaPolaczen();
        przyciskDodajMiasto = new javax.swing.JButton();
        tekstNazwaMiasta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Generowanie danych");

        javax.swing.GroupLayout oknoTabelaPolaczen1Layout = new javax.swing.GroupLayout(oknoTabelaPolaczen1);
        oknoTabelaPolaczen1.setLayout(oknoTabelaPolaczen1Layout);
        oknoTabelaPolaczen1Layout.setHorizontalGroup(
            oknoTabelaPolaczen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        oknoTabelaPolaczen1Layout.setVerticalGroup(
            oknoTabelaPolaczen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        przyciskDodajMiasto.setText("Dodaj");
        przyciskDodajMiasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskDodajMiastoActionPerformed(evt);
            }
        });

        tekstNazwaMiasta.setText("Miasto");
        tekstNazwaMiasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstNazwaMiastaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nazwa miasta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oknoTabelaPolaczen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tekstNazwaMiasta)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(przyciskDodajMiasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tekstNazwaMiasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(przyciskDodajMiasto)
                        .addGap(0, 379, Short.MAX_VALUE))
                    .addComponent(oknoTabelaPolaczen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tekstNazwaMiastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstNazwaMiastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tekstNazwaMiastaActionPerformed

    private void przyciskDodajMiastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskDodajMiastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_przyciskDodajMiastoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private GUI.OknoTabelaPolaczen oknoTabelaPolaczen1;
    private javax.swing.JButton przyciskDodajMiasto;
    private javax.swing.JTextField tekstNazwaMiasta;
    // End of variables declaration//GEN-END:variables
}
