/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Struktury.BazaMiast;
import Struktury.Miasto;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author kuzniarg
 */
public class OknoGeneracji extends javax.swing.JFrame {

    private BazaMiast baza;
    private int aktualny = 0;

    public OknoGeneracji(BazaMiast baza) {
        this.baza = baza;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Generowanie danych - miasto 1");
        this.generujPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tekstNazwaMiasta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tekstPrzejazd = new javax.swing.JTextField();
        przyciskDalej = new javax.swing.JButton();
        panelPolaczen = new javax.swing.JPanel();

        setTitle("Generowanie danych");

        jLabel2.setText("Nazwa miasta");

        jLabel3.setText("Czas przejazu");

        tekstPrzejazd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstPrzejazdActionPerformed(evt);
            }
        });

        przyciskDalej.setText("Dalej");
        przyciskDalej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskDalejActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPolaczenLayout = new javax.swing.GroupLayout(panelPolaczen);
        panelPolaczen.setLayout(panelPolaczenLayout);
        panelPolaczenLayout.setHorizontalGroup(
            panelPolaczenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPolaczenLayout.setVerticalGroup(
            panelPolaczenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przyciskDalej, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPolaczen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tekstNazwaMiasta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tekstPrzejazd, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tekstNazwaMiasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tekstPrzejazd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelPolaczen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(przyciskDalej)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tekstPrzejazdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstPrzejazdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tekstPrzejazdActionPerformed

    private void przyciskDalejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskDalejActionPerformed
        if (tekstNazwaMiasta.getText().compareTo("") == 0 || tekstPrzejazd.getText().compareTo("") == 0)
            return;
            
        this.setTitle("Generowanie danych - miasto " + (aktualny + 2));

        Miasto nowe = new Miasto(tekstNazwaMiasta.getText(), Integer.parseInt(tekstPrzejazd.getText()), baza.getN());
        for (int i = 0; i < baza.getN(); i++) {
            nowe.dodajPolaczenie(i, 0, 0);
            //czysczczenie pól

        }
        baza.setMiasto(aktualny, nowe);

        tekstNazwaMiasta.setText("");
        tekstPrzejazd.setText("");

        aktualny++;
        if (aktualny == baza.getN() - 1) {
            przyciskDalej.setText("Zakończ");
        }
        if (aktualny == baza.getN()) {
            this.wyczysc();
        }
    }//GEN-LAST:event_przyciskDalejActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelPolaczen;
    private javax.swing.JButton przyciskDalej;
    private javax.swing.JTextField tekstNazwaMiasta;
    private javax.swing.JTextField tekstPrzejazd;
    // End of variables declaration//GEN-END:variables

    private void wyczysc() {
        this.aktualny = 0;
        this.setVisible(false);
        this.setTitle("Generowanie danych - miasto 1");
        przyciskDalej.setText("Dalej");
    }

    private void generujPanel() {
        for (int i = 0; i < baza.getN(); i++){
            JLabel opis = new JLabel("Miasto " + (i+1));
            panelPolaczen.add(opis);
            JButton test = new JButton("TEST");
            panelPolaczen.add(test);
            
        }
        
            JButton test = new JButton("TEST");
            panelPolaczen.add(test);
    }
}
